//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Billbank.IEPlugin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Billbank.IEPlugin.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie można odnaleźć konta do wykonania przelewu.
        ///Wspierane typy kont to: {0}..
        /// </summary>
        internal static string AccountNotFound {
            get {
                return ResourceManager.GetString("AccountNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie.
        /// </summary>
        internal static string ButtonNo {
            get {
                return ResourceManager.GetString("ButtonNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tak.
        /// </summary>
        internal static string ButtonYes {
            get {
                return ResourceManager.GetString("ButtonYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Więcej niż jeden zdefiniowany odbiorca ma nazwę: &quot;{0}&quot;.
        ///System wybierze pierwszego z nich.
        ///Aby mieć pewność, że wybierany jest właściwy odbiorca, zmień nazwy odbiorców zdefiniowanych na unikalne..
        /// </summary>
        internal static string BzWbkMoreThanOneDefinedTransfer {
            get {
                return ResourceManager.GetString("BzWbkMoreThanOneDefinedTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak w Twoim koncie bankowym zdefiniowanego przelewu/odbiorcy o nazwie &quot;{0}&quot;.
        ///Czy chcesz wykonać przelew jednorazowy?.
        /// </summary>
        internal static string BzWbkNoDefinedTransfer {
            get {
                return ResourceManager.GetString("BzWbkNoDefinedTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aby automatycznie wypełnić formularz przelewu, wybierz rachunek bankowy, z którego chcesz dokonać opłaty i ponownie kliknij [Zapłać] w podręcznej liście rachunków..
        /// </summary>
        internal static string ChooseAccount {
            get {
                return ResourceManager.GetString("ChooseAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zamknij podręczną listę rachunków.
        /// </summary>
        internal static string ClosePlugin {
            get {
                return ResourceManager.GetString("ClosePlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wystąpił błąd spowodowany prawdopodobnie przez zablokowanie programu &quot;csc.exe&quot; (Visual C# Command Line Compiler). Dalsze działanie tego dodatku nie będzie możliwe. Aby spróbować ponownie zamknij wszystkie okna przeglądarki Internet Explorer i uruchom ją ponownie.
        ///
        ///Aby korzystać z tego dodatku musisz zezwolić na działanie programu &quot;csc.exe&quot;.
        ///
        ///Czy chcesz zobaczyć szczegóły błędu?.
        /// </summary>
        internal static string CscErrorMessage {
            get {
                return ResourceManager.GetString("CscErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokazuje/ukrywa panel.
        /// </summary>
        internal static string DisplayPanel {
            get {
                return ResourceManager.GetString("DisplayPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://irachunki.pl/main/termOfServiceForPLR.html.
        /// </summary>
        internal static string FooterLink {
            get {
                return ResourceManager.GetString("FooterLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to regulamin.
        /// </summary>
        internal static string FooterLinkText {
            get {
                return ResourceManager.GetString("FooterLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korzystając z podręcznej listy rachunków serwisu.
        /// </summary>
        internal static string FooterText1 {
            get {
                return ResourceManager.GetString("FooterText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iRachunki.pl akceptujesz regulamin.
        /// </summary>
        internal static string FooterText2 {
            get {
                return ResourceManager.GetString("FooterText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © Billbank Sp. z o.o..
        /// </summary>
        internal static string FooterText3 {
            get {
                return ResourceManager.GetString("FooterText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Więcej niż jedna płatność ma nazwę: &quot;{0}&quot;.
        ///System wybierze pierwszą z nich.
        ///Aby mieć pewność, że wybierana jest właściwa płatność, zmień nazwy płatności na unikalne..
        /// </summary>
        internal static string InteligoMoreThanOneDefinedTransfer {
            get {
                return ResourceManager.GetString("InteligoMoreThanOneDefinedTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak w Twoim koncie bankowym zdefiniowanego przelewu/odbiorcy o nazwie &quot;{0}&quot;.
        ///Czy chcesz wykonać przelew jednorazowy?.
        /// </summary>
        internal static string InteligoNoDefinedTransfer {
            get {
                return ResourceManager.GetString("InteligoNoDefinedTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaloguj się.
        /// </summary>
        internal static string LoginPlease {
            get {
                return ResourceManager.GetString("LoginPlease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy oznaczyć na rachunku w iRachunki.pl, że zapłacono {0} zł?.
        /// </summary>
        internal static string MarkAsPaidQuestion {
            get {
                return ResourceManager.GetString("MarkAsPaidQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Więcej niż jeden zdefiniowany odbiorca ma nazwę: &quot;{0}&quot;.
        ///System wybierze pierwszego z nich.
        ///Aby mieć pewność, że wybierany jest właściwy odbiorca, zmień nazwy odbiorców zdefiniowanych na unikalne..
        /// </summary>
        internal static string MBankMoreThanOneDefinedTransfer {
            get {
                return ResourceManager.GetString("MBankMoreThanOneDefinedTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak w Twoim koncie bankowym zdefiniowanego przelewu/odbiorcy o nazwie &quot;{0}&quot;.
        ///Czy chcesz wykonać przelew jednorazowy?.
        /// </summary>
        internal static string MBankNoDefinedTransfer {
            get {
                return ResourceManager.GetString("MBankNoDefinedTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Więcej niż jeden zdefiniowany odbiorca ma nazwę: &quot;{0}&quot;.
        ///System wybierze pierwszego z nich.
        ///Aby mieć pewność, że wybierany jest właściwy odbiorca, zmień nazwy odbiorców zdefiniowanych na unikalne..
        /// </summary>
        internal static string MilleniumMoreThanOneDefinedTransfer {
            get {
                return ResourceManager.GetString("MilleniumMoreThanOneDefinedTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak w Twoim koncie bankowym zdefiniowanego przelewu/odbiorcy o nazwie &quot;{0}&quot;.
        ///Czy chcesz wykonać przelew jednorazowy?.
        /// </summary>
        internal static string MilleniumNoDefinedTransfer {
            get {
                return ResourceManager.GetString("MilleniumNoDefinedTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jesteś nie zalogowany.
        /// </summary>
        internal static string NotLogged {
            get {
                return ResourceManager.GetString("NotLogged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapłać.
        /// </summary>
        internal static string Pay {
            get {
                return ResourceManager.GetString("Pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak w Twoim koncie bankowym zdefiniowanego przelewu/odbiorcy o nazwie &quot;{0}&quot;.
        ///Czy chcesz wykonać przelew jednorazowy?.
        /// </summary>
        internal static string Pekao24NoDefinedTransfer {
            get {
                return ResourceManager.GetString("Pekao24NoDefinedTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Więcej niż jeden zdefiniowany odbiorca ma nazwę: &quot;{0}&quot;.
        ///System wybierze pierwszego z nich.
        ///Aby mieć pewność, że wybierany jest właściwy odbiorca, zmień nazwy odbiorców zdefiniowanych na unikalne..
        /// </summary>
        internal static string PkoMoreThanOneDefinedTransfer {
            get {
                return ResourceManager.GetString("PkoMoreThanOneDefinedTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak w Twoim koncie bankowym zdefiniowanego przelewu/odbiorcy o nazwie &quot;{0}&quot;.
        ///Czy chcesz wykonać przelew jednorazowy?.
        /// </summary>
        internal static string PkoNoDefinedTransfer {
            get {
                return ResourceManager.GetString("PkoNoDefinedTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Witaj.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numer konta bankowego odbiorcy przelewu różni się od numeru podanego w opłacanym rachunku.
        ///Sprawdź poprawność numeru konta bankowego odbiorcy zanim potwierdzisz wykonanie przelewu..
        /// </summary>
        internal static string WrongAccountNo {
            get {
                return ResourceManager.GetString("WrongAccountNo", resourceCulture);
            }
        }
    }
}
