//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Billbank.IEPlugin {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "8.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.6.24")]
        public string PluginVersion {
            get {
                return ((string)(this["PluginVersion"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://irachunki.pl/miniWeb/")]
        public string LocationUrl {
            get {
                return ((string)(this["LocationUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("iRachunki.pl")]
        public string PluginTitle {
            get {
                return ((string)(this["PluginTitle"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>https://www.mbank.com.pl</string>
  <string>https://secure.inteligo.com.pl</string>
  <string>https://www.pekao24.pl</string>
  <string>https://ssl.bsk.com.pl</string>
  <string>https://www.centrum24.pl</string>
  <string>https://www.ipko.pl</string>
  <string>https://www.millenet.pl</string>
  <string>https://www.managerland.pl</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ProviderId {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ProviderId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Billbank.IEPlugin.Provider.MBankProvider</string>
  <string>Billbank.IEPlugin.Provider.InteligoProvider</string>
  <string>Billbank.IEPlugin.Provider.Pekao24Provider</string>
  <string>Billbank.IEPlugin.Provider.IngProvider</string>
  <string>Billbank.IEPlugin.Provider.BzWbkProvider</string>
  <string>Billbank.IEPlugin.Provider.PkoProvider</string>
  <string>Billbank.IEPlugin.Provider.MilleniumProvider</string>
  <string>Billbank.IEPlugin.Provider.MilleniumProvider</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ProviderClass {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ProviderClass"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://irachunki.pl/miniWeb/chooseBank.action?version=")]
        public string ChoseBankLink {
            get {
                return ((string)(this["ChoseBankLink"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ReloadCount {
            get {
                return ((int)(this["ReloadCount"]));
            }
            set {
                this["ReloadCount"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int MaxReload {
            get {
                return ((int)(this["MaxReload"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://irachunki.pl/miniWeb/logout.action")]
        public string LogoutUrl {
            get {
                return ((string)(this["LogoutUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mJump(\'MCP/server/MTPredefinedAccount.jsp\',1, \'?\')")]
        public string Pekao24PredefinedJspUrl {
            get {
                return ((string)(this["Pekao24PredefinedJspUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mJump(\'MCP/server/MTNotPredefinedAccount.jsp\',1, \'?\')")]
        public string Pekao24NotPredefinedJspUrl {
            get {
                return ((string)(this["Pekao24NotPredefinedJspUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mJump(\'/MCP/MTPredefinedAccount.htm\',1, \'?\')")]
        public string Pekao24PredefinedHtmUrl {
            get {
                return ((string)(this["Pekao24PredefinedHtmUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mJump(\'/MCP/MTNotPredefinedAccount.htm\',1, \'?\')")]
        public string Pekao24NotPredefinedHtmUrl {
            get {
                return ((string)(this["Pekao24NotPredefinedHtmUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>zobacz wskazówki</string>
  <string>załóż bezpłatne konto</string>
  <string>zobacz demo</string>
  <string>zamknij to okienko</string>
  <string>regulaminem</string>
  <string>zobacz co zrobić</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection LinksInnerHtmlToHandle {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["LinksInnerHtmlToHandle"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://irachunki.pl/miniWeb/banksList.action?version=")]
        public string BanksListLink {
            get {
                return ((string)(this["BanksListLink"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Podręczna Lista Rachunków")]
        public string PluginTooltip {
            get {
                return ((string)(this["PluginTooltip"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://irachunki.pl/plrInstalled.action")]
        public string FirstExecutionLink {
            get {
                return ((string)(this["FirstExecutionLink"]));
            }
        }
    }
}
